# Generated by Django 3.0.5 on 2020-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('appears_in', models.CharField(max_length=1024)),
                ('home_planet', models.CharField(max_length=1024)),
                ('height', models.IntegerField()),
            ],
        ),
    ]
